# How many seconds the combat lasts for
combat-timer: 15

chat:
  # The message for going into combat (CHAT)
  on-message: '&cYou are now in combat!'

  # The message for going out of combat (CHAT)
  off-message: '&cYou are now out of combat!'

  # If the plugin will use chat messages
  # If false it will still print when the players dies during combat
  use: true

actionbar:
  # The message for going into combat (ACTIONBAR)
  on-message: '&cYou are now in combat for %combatlogger_timeformatted%!'

  # The message for going out of combat (ACTIONBAR)
  off-message: '&cYou are now out of combat!'

  # If the plugin will use actionbar messages
  use: true

# The punishment activates when a user logs out during combat
# Types: "KILL", "BAN:TIMEINSECONDS:REASON`{timeRemaining}=CURRENTBANTIME`"
# To remove a punishment just remove the line examaple,
# this will only kill the player when they log out during combat
#-----------
# punishment:
#   - "KILL"
#-----------
#To disable punishments you can do `punishments: []`
punishment:
  - "BAN:10:&cYou logged out during combat \n Please wait %combatlogger_timeformatted%"
  - "KILL"