#Change how many seconds it takes for you to get out of combat
combat-timer: 10

#The message for going into combat
combat-message: '&cYou are now in combat!'

#The message for going out of combat
combat-off-message: '&cYou are now out of combat!'