name: CombatLogger
version: 1.0.6
main: com.keurig.combatlogger.CombatLogger
authors: [Keurig]
description: A simple combat logger plugin!
api-version: 1.13
permissions:
  combatlogger.admin:
    default: false